---
- name: Ensure local Administrator passwords don't expire
  hosts: windows
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Set local Administrator password to never expire
      win_user:
        name: Administrator
        password_never_expires: yes
      tags:
        - local_password_expiry
