- name: Join machines to domain
  hosts:
    - windows*
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Set DNS
      ansible.windows.win_dns_client:
        adapter_names: '*'
        dns_servers: "{{ hostvars['domain_controller']['ansible_host'] }}"

    - name: Join domain
      ansible.windows.win_domain_membership:
        dns_domain_name: example.corp
        domain_admin_user: example.corp\m.magdelena
        domain_admin_password: 10Ek!d0S[1qX*d[=o^k&
        state: domain
      register: domain_join

    - name: Reboot
      ansible.windows.win_reboot:
      when: domain_join.reboot_required  
