- name: Install and configure Elastic
  hosts: 
    - elastic
  become: yes

  tasks:
    - name: Set hostname
      hostname:
        name: "{{ hostname }}"

    ## Gather installed packages for checks ##
    - name: Gather package facts
      package_facts:
        manager: apt

    ## Pre-req installs for ELK ##
    - name: install gpg, pip, and cron
      apt:
        name: 
          - gpg
          - python3-pip
          - cron
        state: present
        update_cache: yes
      when: '"elasticsearch" not in ansible_facts.packages'

    - name: Add elastic GPG key
      ansible.builtin.apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        keyring: /usr/share/keyrings/elasticsearch-keyring.gpg
        state: present
      when: '"elasticsearch" not in ansible_facts.packages'

    - name: Add Elastic repo
      shell: echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-8.x.list
      when: '"elasticsearch" not in ansible_facts.packages'

    ## Installation/update Elasticsearch and Kibana ##
    - name: Install Elasticsearch
      ansible.builtin.apt:
        name: elasticsearch
        update_cache: yes
        state: latest

    - name: Install Kibana
      ansible.builtin.apt:
        name: kibana
        update_cache: yes
        state: latest

    ## Start the Elasticsearch service ##
    - name: Start Elastic and enable service
      ansible.builtin.service:
        name: elasticsearch
        enabled: yes
        state: started

    - name: Pause for 1 minute for initial Elasticsearch build
      ansible.builtin.pause:
        minutes: 1
      when: '"elasticsearch" not in ansible_facts.packages'

    ## Gather facts/data for setting up Elastic if this is the first run ##
    - name: Reset/Get the password for the elastic user
      shell: yes | /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic -s
      register: elastic_password
      when: '"elasticsearch" not in ansible_facts.packages'

    ## Store Elastic password ##
    - name: Write Elastic passowrd to file on host
      copy:
        content: |
          {{ elastic_password.stdout }}
        dest: /etc/elasticsearch/elastic-usr-pwd.txt
      become: yes
      when: '"elasticsearch" not in ansible_facts.packages'

    - name: Generate Kibana enrollment token
      shell: /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana --url "https://127.0.0.1:9200"
      register: kibana_enrollment_token
      when: '"elasticsearch" not in ansible_facts.packages'

    ## Enroll and set up Kibana ##
    - name: Enroll Kibana
      shell: /usr/share/kibana/bin/kibana-setup --enrollment-token {{ kibana_enrollment_token.stdout }}
      when: '"elasticsearch" not in ansible_facts.packages'

    - name: Remove elasticsearch hosts in Kibana config
      shell: sudo sed -i '/^elasticsearch\.hosts/s/.*/\#/g' /etc/kibana/kibana.yml 
      when: '"elasticsearch" not in ansible_facts.packages'

    - name: Remove incorrect autogenerated xpack in Kibana config
      shell: sudo sed -i '/^xpack\.security/s/.*/\#/g' /etc/kibana/kibana.yml
      when: '"elasticsearch" not in ansible_facts.packages'

    - name: Generate random encryption key
      shell: echo $RANDOM | md5sum | head -c 32; echo;
      register: encryption_key
      when: '"elasticsearch" not in ansible_facts.packages'

    - name: Add new elasticsearch hosts in Kibana config
      blockinfile:
        path: /etc/kibana/kibana.yml
        content: "server.host: '0.0.0.0'\nelasticsearch.hosts: ['https://127.0.0.1:9200']\nxpack.security.authc.providers:\n  anonymous.anonymous1:\n    order: 0\n    credentials:\n      username: \"elastic\"\n      password: \"{{ elastic_password.stdout }}\"\n\nxpack.encryptedSavedObjects.encryptionKey: '{{ encryption_key.stdout }}'"
      when: '"elasticsearch" not in ansible_facts.packages'

    - name: Restart Kibana to force config refresh and enable service
      ansible.builtin.service:
        name: kibana
        enabled: yes
        state: restarted
      when: '"elasticsearch" not in ansible_facts.packages'
