---
- name: Setup Domain Controller
  hosts: domain_controller
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Install AD-Domain-Services Role
      ansible.windows.win_feature:
        name: AD-Domain-Services
        state: present

    - name: Install DNS Role
      ansible.windows.win_feature:
        name: DNS
        state: present

    - name: Promote server to a Domain Controller
      ansible.windows.win_domain:
        dns_domain_name: "{{ hostvars[inventory_hostname]['domain_name'] }}"
        domain_netbios_name: "{{ hostvars[inventory_hostname]['netbios_name'] }}"
        safe_mode_password: "{{ hostvars[inventory_hostname]['safe_mode_password'] }}"
        domain_admin_user: "{{ hostvars[inventory_hostname]['ansible_user'] }}"
        domain_admin_password: "{{ hostvars[inventory_hostname]['ansible_password'] }}"
        state: domain_controller
        domain_mode: WinThreshold
        forest_mode: WinThreshold
      register: domain_result

    - name: Reboot if necessary
      ansible.windows.win_reboot:
        reboot_timeout: 600
      when: domain_result.reboot_required

    - name: Install Additional Domain Controller Features
      ansible.windows.win_feature:
        name:
          - RSAT-AD-Tools
          - RSAT-AD-AdminCenter
          - RSAT-DNS-Server
        state: present

    - name: Create DNS record for Elastic
      community.windows.win_dns_record:
        name: "elk01"
        type: "A"
        value: "{{ hostvars['elastic']['ansible_host'] }}"
        zone: "example.corp"
