---
- name: Setup Domain Controller
  hosts: domain_controller
  vars:
    domain_name: "example.corp"
    netbios_name: "EXAMPLE"
    safe_mode_password: "}e5K@Z98rE_W"
    domain_admin_username: "Administrator"
    domain_admin_password: ")6%*i4Uzv!Bn?GZ7LM?7I-KT?ac&3IhL"
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Install AD-Domain-Services Role
      ansible.windows.win_feature:
        name: AD-Domain-Services
        state: present

    - name: Install DNS Role
      ansible.windows.win_feature:
        name: DNS
        state: present

    - name: Promote server to a Domain Controller
      ansible.windows.win_domain:
        dns_domain_name: "{{ domain_name }}"
        domain_netbios_name: "{{ netbios_name }}"
        safe_mode_password: "{{ safe_mode_password }}"
        domain_admin_user: "{{ domain_admin_username }}"
        domain_admin_password: "{{ domain_admin_password }}"
        state: domain_controller
        domain_mode: WinThreshold
        forest_mode: WinThreshold
      register: domain_result

    - name: Reboot if necessary
      ansible.windows.win_reboot:
        reboot_timeout: 600
      when: domain_result.reboot_required

    - name: Install Additional Domain Controller Features
      ansible.windows.win_feature:
        name:
          - RSAT-AD-Tools
          - RSAT-AD-AdminCenter
          - RSAT-DNS-Server
        state: present

    - name: Create DNS record for Elastic
      community.windows.win_dns_record:
        name: "elk01"
        type: "A"
        value: "{{ hostvars['elastic']['ansible_host'] }}"
        zone: "example.corp"
