---
- name: Disable and refuse machine account password GPO settings on Domain Controller
  hosts: domain_controller
  tasks:
    - name: create a directory to hold the templates
      win_file:
        path: C:\setup
        state: directory
  
    - name: Transfer the disable_machine_account_password PowerShell script to domain controller
      win_copy:
        src: ./scripts/disable_machine_account_password.ps1
        dest: C:\setup\disable_machine_account_password.ps1

    - name: Execute the disable_machine_account_password script
      win_command: powershell.exe -ExecutionPolicy ByPass -File C:\setup\disable_machine_account_password.ps1
      register: disable_password_script_result

    - name: Display disable_machine_account_password script output
      debug:
        var: disable_password_script_result.stdout_lines

    - name: Copy the refuse_password_change PowerShell script to DC
      win_copy:
        src: ./scripts/refuse_password_change.ps1
        dest: C:\setup\refuse_password_change.ps1

    - name: Execute the refuse_password_change PowerShell script on DC
      win_command: powershell.exe -ExecutionPolicy Bypass -File C:\setup\refuse_password_change.ps1
      register: refuse_password_script_result

    - name: Display refuse_password_change script output
      debug:
        var: refuse_password_script_result.stdout_lines

    - name: Delete C:\Setup directory
      win_shell: |
        Remove-Item -Path C:\Setup -Recurse -Force
      register: delete_setup_result
      ignore_errors: yes  # Ignore errors if the directory doesn't exist
