---
- hosts: domain_controller
  tasks:

    - name: create a directory to hold the templates
      win_file:
        path: C:\setup
        state: directory

    - name: Copy PowerShell script to remote server
      win_copy:
        src: ./scripts/import_gpo.ps1
        dest: C:\setup\import_gpo.ps1

    - name: Copy backuped GPO to remote server
      win_copy:
        src: ./backup_gpo/DefenderPolicySettings/{7C35599B-11D6-487C-9BCF-42E136547BAC}
        dest: C:\setup\backup_gpo\

    - name: Execute the PowerShell script to import and link backed-up GPO
      win_command: powershell.exe -ExecutionPolicy Bypass -File C:\setup\import_gpo.ps1
      register: result

    - name: Display script output
      debug:
        var: result.stdout_lines

    - name: Delete C:\Setup directory
      win_shell: |
        Remove-Item -Path C:\Setup -Recurse -Force
      register: delete_setup_result
      ignore_errors: yes  # Ignore errors if the directory doesn't exist
