---
- hosts: domain_controller
  tasks:
    - name: create a directory to hold the templates
      win_file:
        path: C:\setup
        state: directory
  
    - name: Copy PowerShell script to remote server
      win_copy:
        src: ./scripts/import_event_forwarder_server_gpo.ps1
        dest: C:\setup\import_event_forwarder_server_gpo.ps1

    - name: Copy backuped GPO to remote server
      win_copy:
        src: ./backup_gpo/WEF_WEC/WEF-Server/{E34D36BE-9B45-4F8A-8B8F-EC6E0DF5CF0D}
        dest: C:\setup\backup_gpo\

    - name: Execute the PowerShell script to import and link backed-up GPO
      win_command: powershell.exe -ExecutionPolicy Bypass -File C:\setup\import_event_forwarder_server_gpo.ps1
      register: result

    - name: Display script output
      debug:
        var: result.stdout_lines
    
    - name: Copy Powershell script to remote server
      win_copy:
        src: ./scripts/import_event_forwarder_client_gpo.ps1
        dest: C:\setup\import_event_forwarder_client_gpo.ps1
    
    - name: Copy backup of GPO to remote server
      win_copy:
        src: ./backup_gpo/WEF_WEC/WEF-Client/{EEE3C0A9-02B7-443B-BA10-B86B687A1B44}
        dest: C:\setup\backup_gpo\

    - name: Execute the PowerShell script to import and link backed-up GPO
      win_command: powershell.exe -ExecutionPolicy Bypass -File C:\setup\import_event_forwarder_client_gpo.ps1
      register: result

    - name: Display script output
      debug:
        var: result.stdout_lines

    - name: Delete C:\Setup directory
      win_shell: |
        Remove-Item -Path C:\Setup -Recurse -Force
      register: delete_setup_result
      ignore_errors: yes  # Ignore errors if the directory doesn't exist